const brandIcons: Record<string, string> = {
  "Vue.js": "vuedotjs",
  "Vue": "vuedotjs",
  "React Native": "reactnative",
  "React": "react",
  "Laravel": "laravel",
  "Leaflet": "leaflet",
  "Node.js": "nodedotjs",
  "Express": "express",
  "TypeScript": "typescript",
  "Socket.IO": "socketdotio",
  "PostgreSQL": "postgresql",
  "Sequelize": "sequelize",
  "Inertia.js": "inertia",
  "Twilio": "twilio",
  "WhatsApp": "whatsapp",
  "Android Studio": "androidstudio",
  "Google Calendar": "googlecalendar",
  "Expo": "expo",
  "PHP": "php",
  "CodeIgniter": "codeigniter",
  "MySQL": "mysql",
  "JavaScript": "javascript",
  "HTML": "html5",
  "CSS": "css3",
  "Bootstrap": "bootstrap",
  "Tailwind": "tailwindcss",
  "Mailgun": "mailgun",
  "OpenAI": "openai",
  "Mapbox": "mapbox",
  "Git": "git",
  "GitHub": "github",
  "Postman": "postman",
  "Cloudflare": "cloudflare",
  "Docker": "docker",
};

const genericIcons: Record<string, string> = {
  "email": "email",
  "gps": "gps",
  "map": "map",
  "ai": "ai",
  "mobile": "mobile",
  "dashboard": "dashboard",
  "code": "code",
};

const genericMap: [string, string][] = [
  ["App Móvil", "mobile"],
  ["Mobile App", "mobile"],
  ["Dashboard Web", "dashboard"],
  ["Web Dashboard", "dashboard"],
  ["Servicios GPS", "gps"],
  ["GPS services", "gps"],
  ["GPS", "gps"],
  ["Mapas", "map"],
  ["Maps", "map"],
  ["Mapa", "map"],
  ["Servicios de correo", "email"],
  ["Email services", "email"],
  ["Correo", "email"],
  ["Servicios de IA", "ai"],
  ["AI services", "ai"],
  ["IA", "ai"],
  ["Turf", "map"],
  ["Psychometric evaluation system", "psychometric"],
  ["Sistema de evaluaciones psicométricas", "psychometric"],
  ["evaluaciones psicométricas", "ai"],
  ["psicométrica", "ai"],
  ["Diseño Responsive", "code"],
  ["Responsive Design", "code"],
  ["Desarrollo de APIs", "code"],
  ["API Development", "code"],
  ["Sistemas en Tiempo Real", "code"],
  ["Real-Time Systems", "code"],
  ["Autenticación", "code"],
  ["Authentication", "code"],
  ["Control de Acceso Basado en Roles", "code"],
  ["Role-Based Access Control", "code"],
  ["Compilaciones Android", "mobile"],
  ["Android Builds", "mobile"],
  ["Servicios en Segundo Plano", "mobile"],
  ["Background Services", "mobile"],
  ["Generación de PDF", "code"],
  ["PDF Generation", "code"],
  ["Exportaciones a Excel", "code"],
  ["Excel Exports", "code"],
  ["Sistemas de Notificaciones", "code"],
  ["Notification Systems", "code"],
  ["Flujos de Chatbot", "ai"],
  ["Chatbot Workflows", "ai"],
  ["Sincronización Offline", "code"],
  ["Offline Sync", "code"],
  ["Geocercas", "map"],
  ["Geofencing", "map"],
  ["Interfaces Geoespaciales", "map"],
  ["Geospatial Interfaces", "map"],
  ["Actualizaciones OTA", "code"],
  ["OTA Updates", "code"],
];

export function getSkillIcon(skill: string): string | undefined {
  if (brandIcons[skill]) return `/icons/${brandIcons[skill]}.svg`;
  if (skill === "Opencode") return "/icons/opencode.png";
  if (skill === "Codex") return "/icons/codex.png";
  for (const [key, value] of Object.entries(brandIcons)) {
    if (skill.includes(key)) return `/icons/${value}.svg`;
  }
  for (const [pattern, icon] of genericMap) {
    if (skill.includes(pattern)) return `/icons/${icon}.svg`;
  }
  return undefined;
}
